Repository rust-embedded/discovery, pull requests merged in 2020-05, with the labels that each got.

#161 Add section [Bluetooth setup] -> [AT commands]
  src/SUMMARY.md
Labels: S-waiting-on-bors

#169 Chapter 06: Update README
  src/06-hello-world/README.md
Labels: S-waiting-on-bors

#179 Update macOS setup instructions for ARM toolchain.
  src/03-setup/macos.md
Labels: S-waiting-on-bors, T-resources

#225 Add knowledge requirement for hex and bitwise operations.
  src/02-requirements/README.md
Labels: S-waiting-on-review, T-resources

#232 Rework the "where to go from here" section to track items we want to teach
  src/explore.md
Labels: S-waiting-on-review, T-resources

#230 Removed overwhelming info, added context to "Meet your Hardware"
  src/04-meet-your-hardware/README.md
Labels: S-waiting-on-author, T-resources

#233 Batch of styling and formatting changes
  src/01-background/README.md
  src/03-setup/README.md
  src/03-setup/linux.md
  src/03-setup/verify.md
  src/04-meet-your-hardware/README.md
  src/05-led-roulette/build-it.md
  src/05-led-roulette/flash-it.md
  src/06-hello-world/README.md
  src/10-serial-communication/README.md
  src/10-serial-communication/loopbacks.md
  src/10-serial-communication/nix-tooling.md
  src/10-serial-communication/windows-tooling.md
  src/11-usart/README.md
  src/11-usart/buffer-overrun.md
  src/11-usart/echo-server.md
  src/11-usart/receive-a-single-byte.md
  src/11-usart/send-a-single-byte.md
  src/11-usart/send-a-string.md
  src/12-bluetooth-setup/README.md
  src/12-bluetooth-setup/at-commands.md
  src/12-bluetooth-setup/linux.md
  src/12-bluetooth-setup/loopback.md
  src/13-serial-over-bluetooth/README.md
  src/SUMMARY.md
Labels: S-waiting-on-review, T-resources

#241 Update link to eCompass calibration note
  src/15-led-compass/calibration.md
Labels: S-waiting-on-review, T-resources

#242 Minor typo in type-safe-manipulation.md
  src/07-registers/type-safe-manipulation.md
Labels: S-waiting-on-review, T-resources
